apiVersion: v2
name: pomerium-zero
description: A Helm chart for deploying Pomerium Zero
type: application
version: 0.31.0
appVersion: v0.31.0
home: https://www.pomerium.com/
icon: https://www.pomerium.com/static-img/favicon.svg
sources:
  - https://github.com/pomerium/pomerium
maintainers:
  - name: Pomerium Team
    email: support@pomerium.com
keywords:
  - pomerium
  - zero
  - identity-aware proxy
  - access proxy
